# Generated by Django 2.1.2 on 2018-12-06 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_scraper', '0003_auto_20181119_1912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='highlighted',
            new_name='is_highlighted',
        ),
        migrations.AddField(
            model_name='job',
            name='job_url',
            field=models.URLField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.CharField(max_length=5000),
        ),
    ]
