# Generated by Django 2.1.2 on 2018-12-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_scraper', '0004_auto_20181206_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
    ]
