# Generated by Django 2.1.2 on 2018-12-10 11:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('job_scraper', '0005_job_is_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
