# Generated by Django 2.1.2 on 2019-04-04 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_scraper', '0013_add_company_descriptions'),
    ]

    operations = [
        migrations.RunSQL(
            """
            INSERT INTO 'Companies'('name', 'logo') VALUES ('Hatch Entertainment Oy', 'hatch_entertainment.png.png');
            INSERT INTO 'Companies'('name', 'logo') VALUES ('Qentinel', 'qentinel.png');
            INSERT INTO 'Companies'('name', 'logo') VALUES ('Tuxera', 'tuxera.png');
            INSERT INTO 'Companies'('name', 'logo') VALUES ('Taiste', 'taiste.png');
            INSERT INTO 'Companies'('name', 'logo') VALUES ('Intopalo Digital Oy', 'intopalo_digital.png');
            INSERT INTO 'Companies'('name', 'logo') VALUES ('Reaktor', 'reaktor.png');
            INSERT INTO 'Companies'('name', 'logo') VALUES ('Bittium', 'bittium.png');
            INSERT INTO 'Companies'('name', 'logo') VALUES ('Accenture', 'accenture.png');
            INSERT INTO 'Companies'('name', 'logo') VALUES ('Efima', 'efima.png');
            INSERT INTO 'Companies'('name', 'logo') VALUES ('Napa', 'napa.png');
            INSERT INTO 'Companies'('name', 'logo') VALUES ('AJR solutions Oy', 'ajr_solutions.png');
            INSERT INTO 'Companies'('name', 'logo') VALUES ('Anders', 'anders.png');
            INSERT INTO 'Companies'('name', 'logo') VALUES ('Small Giant Games', 'small_giant_games.png');
            INSERT INTO 'Companies'('name', 'logo') VALUES ('Oura', 'oura.png');
            INSERT INTO 'Companies'('name', 'logo') VALUES ('Matchmade', 'matchmade.png');
            INSERT INTO 'Companies'('name', 'logo') VALUES ('ultimate.ai', 'ultimate_ai.png');
            INSERT INTO 'Companies'('name', 'logo') VALUES ('Jolla', 'jolla.png');
            INSERT INTO 'Companies'('name', 'logo') VALUES ('Yousician', 'yousician.png');
            INSERT INTO 'Companies'('name', 'logo') VALUES ('Leadfeeder', 'leadfeeder.png');
            INSERT INTO 'Companies'('name', 'logo') VALUES ('ZenRobotics', 'zenrobotics.png');
            INSERT INTO 'Companies'('name', 'logo') VALUES ('Callstats.io', 'callstats_io.png');
            INSERT INTO 'Companies'('name', 'logo') VALUES ('Bitbar', 'bitbar.png');
            INSERT INTO 'Companies'('name', 'logo') VALUES ('Aiven', 'aiven.png');
            INSERT INTO 'Companies'('name', 'logo') VALUES ('SSH Communications Security', 'ssh_communications_security.png');
            INSERT INTO 'Companies'('name', 'logo') VALUES ('Vizor', 'vizor.png');
            INSERT INTO 'Companies'('name', 'logo') VALUES ('Frosmo', 'frosmo.png');
            INSERT INTO 'Companies'('name', 'logo') VALUES ('Vizor', 'vizor.png');
            INSERT INTO 'Companies'('name', 'logo') VALUES ('Everywear Games Oy', 'everywear_games.png');
            INSERT INTO 'Companies'('name', 'logo') VALUES ('Supermetrics', 'supermetrics.png');
            """
        )
    ]
