# Generated by Django 2.1.2 on 2019-04-23 17:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('job_scraper', '0016_auto_20190422_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSearches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what_entry', models.CharField(blank=True, max_length=500, null=True)),
                ('where_entry', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'UserSearches',
            },
        ),
    ]
