# Generated by Django 2.1.2 on 2019-04-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_scraper', '0018_new_companies'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersearches',
            options={'verbose_name_plural': 'UserSearches'},
        ),
        migrations.AddField(
            model_name='company',
            name='logo100',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
