# Generated by Django 2.1.2 on 2019-05-13 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_scraper', '0020_added_logo_100px'),
    ]

    operations = [
        migrations.RunSQL(
            """
            INSERT INTO 'Companies'('name', 'logo', 'logo100') VALUES ('Forenom', 'forenom.png', 'forenom_100.png');
            INSERT INTO 'Companies'('name', 'logo', 'logo100') VALUES ('Bitville', 'bitville.png', 'bitville_100.png');
            INSERT INTO 'Companies'('name', 'logo', 'logo100') VALUES ('Varian Medical Systems', 'varian_medical_systems.png', 'varian_medical_systems_100.png');
            INSERT INTO 'Companies'('name', 'logo', 'logo100') VALUES ('Valmet', 'valmet.png', 'valmet_100.png');
            INSERT INTO 'Companies'('name', 'logo', 'logo100') VALUES ('Metso', 'metso.png', 'metso_100.png');
            INSERT INTO 'Companies'('name', 'logo', 'logo100') VALUES ('Nokian Tyres', 'nokian_tyres.png', 'nokian_tyres_100.png');
            INSERT INTO 'Companies'('name', 'logo', 'logo100') VALUES ('Elomatic', 'elomatic.png', 'elomatic_100.png');
            INSERT INTO 'Companies'('name', 'logo', 'logo100') VALUES ('Meyer Turku', 'meyer_turku.png', 'meyer_turku_100.png');
            INSERT INTO 'Companies'('name', 'logo', 'logo100') VALUES ('Almaco', 'almaco.png', 'almaco_100.png');
            INSERT INTO 'Companies'('name', 'logo', 'logo100') VALUES ('Vapo', 'vapo.png', 'vapo_100.png');
            INSERT INTO 'Companies'('name', 'logo', 'logo100') VALUES ('Alma Media', 'alma.png', 'alma_100.png');
            INSERT INTO 'Companies'('name', 'logo', 'logo100') VALUES ('Pöyry', 'poyry.png', 'poyry_100.png');
            INSERT INTO 'Companies'('name', 'logo', 'logo100') VALUES ('UPM', 'upm.png', 'upm_100.png');
            INSERT INTO 'Companies'('name', 'logo', 'logo100') VALUES ('Mirum', 'mirum.png', 'mirum_100.png');
            INSERT INTO 'Companies'('name', 'logo', 'logo100') VALUES ('Krogerus', 'krogerus.png', 'krogerus_100.png');
            INSERT INTO 'Companies'('name', 'logo', 'logo100') VALUES ('Siemens', 'siemens.png', 'siemens_100.png');
            INSERT INTO 'Companies'('name', 'logo', 'logo100') VALUES ('Posti', 'posti.png', 'posti_100.png');
            INSERT INTO 'Companies'('name', 'logo', 'logo100') VALUES ('Attendo', 'attendo.png', 'attendo_100.png');
            INSERT INTO 'Companies'('name', 'logo', 'logo100') VALUES ('Caverion', 'caverion.png', 'caverion_100.png');
            INSERT INTO 'Companies'('name', 'logo', 'logo100') VALUES ('Canter', 'canter.png', 'canter_100.png');
            INSERT INTO 'Companies'('name', 'logo', 'logo100') VALUES ('Gapps', 'gapps.png', 'gapps_100.png');
            INSERT INTO 'Companies'('name', 'logo', 'logo100') VALUES ('Profit Software', 'profit_software.png', 'profit_software_100.png');
            INSERT INTO 'Companies'('name', 'logo', 'logo100') VALUES ('Innokas medical', 'innokas_medical.png', 'innokas_medical_100.png');
            INSERT INTO 'Companies'('name', 'logo', 'logo100') VALUES ('Tikkurila', 'tikkurila.png', 'tikkurila_100.png');
            INSERT INTO 'Companies'('name', 'logo', 'logo100') VALUES ('Frogmind', 'frogmind.png', 'frogmind_100.png');
            INSERT INTO 'Companies'('name', 'logo', 'logo100') VALUES ('Zynga', 'zynga.png', 'zynga_100.png');
            """
        )
    ]
