# Generated by Django 2.1.2 on 2019-05-13 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_scraper', '0020_added_logo_100px'),
    ]

    operations = [
        migrations.RunSQL(
            """
            INSERT INTO 'Companies'('name', 'logo') VALUES ('Forenom', 'forenom.png');
            INSERT INTO 'Companies'('name', 'logo') VALUES ('Bitville', 'bitville.png');
            INSERT INTO 'Companies'('name', 'logo') VALUES ('Varian Medical Systems', 'varian_medical_systems.png');
            INSERT INTO 'Companies'('name', 'logo') VALUES ('Valmet', 'valmet.png');
            INSERT INTO 'Companies'('name', 'logo') VALUES ('Metso', 'metso.png');
            INSERT INTO 'Companies'('name', 'logo') VALUES ('Nokian Tyres', 'nokian_tyres.png');
            INSERT INTO 'Companies'('name', 'logo') VALUES ('Elomatic', 'elomatic.png');
            INSERT INTO 'Companies'('name', 'logo') VALUES ('Meyer Turku', 'meyer_turku.png');
            INSERT INTO 'Companies'('name', 'logo') VALUES ('Almaco', 'almaco.png');
            INSERT INTO 'Companies'('name', 'logo') VALUES ('Vapo', 'vapo.png');
            INSERT INTO 'Companies'('name', 'logo') VALUES ('Alma Media', 'alma.png');
            INSERT INTO 'Companies'('name', 'logo') VALUES ('Pöyry', 'poyry.png');
            INSERT INTO 'Companies'('name', 'logo') VALUES ('UPM', 'upm.png');
            INSERT INTO 'Companies'('name', 'logo') VALUES ('Mirum', 'mirum.png');
            INSERT INTO 'Companies'('name', 'logo') VALUES ('Krogerus', 'krogerus.png');
            INSERT INTO 'Companies'('name', 'logo') VALUES ('Siemens', 'siemens.png');
            INSERT INTO 'Companies'('name', 'logo') VALUES ('Posti', 'posti.png');
            INSERT INTO 'Companies'('name', 'logo') VALUES ('Attendo', 'attendo.png');
            INSERT INTO 'Companies'('name', 'logo') VALUES ('Caverion', 'caverion.png');
            INSERT INTO 'Companies'('name', 'logo') VALUES ('Canter', 'canter.png');
            INSERT INTO 'Companies'('name', 'logo') VALUES ('Gapps', 'gapps.png');
            INSERT INTO 'Companies'('name', 'logo') VALUES ('Profit Software', 'profit_software.png');
            INSERT INTO 'Companies'('name', 'logo') VALUES ('Innokas medical', 'innokas_medical.png');
            INSERT INTO 'Companies'('name', 'logo') VALUES ('Tikkurila', 'tikkurila.png');
            INSERT INTO 'Companies'('name', 'logo') VALUES ('Frogmind', 'frogmind.png');
            INSERT INTO 'Companies'('name', 'logo') VALUES ('Zynga', 'zynga.png');
            """
        )
    ]
