# Generated by Django 2.1.2 on 2019-05-28 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_scraper', '0021_new_companies'),
    ]

    operations = [
        migrations.RunSQL(
            """
            INSERT INTO 'Companies'('name', 'logo', 'logo100', 'description') VALUES ('Posti', 'posti.png', 'posti_100.png', '<p>Posti is the leading postal and logistics service company in Finland. Our core business include postal services, parcels, freight and logistics services. We have the widest network coverage in Finland and we visit about three million households and companies every weekday. We manage the flow of everyday life in 10 countries.</p>');
            """
        )
        ]
