# Generated by Django 2.1.2 on 2019-08-07 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_scraper', '0026_new_companies'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('swedish_name', models.CharField(blank=True, default=None, max_length=64, null=True)),
            ],
            options={
                'verbose_name_plural': 'cities',
                'db_table': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='JobCityMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_scraper.City')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_scraper.Job')),
            ],
            options={
                'db_table': 'JobCityMap',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'db_table': 'Regions',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job_scraper.Region'),
        ),
        migrations.AddField(
            model_name='job',
            name='cities',
            field=models.ManyToManyField(through='job_scraper.JobCityMap', to='job_scraper.City'),
        ),
    ]
