# Generated by Django 2.1.2 on 2019-08-09 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_scraper', '0028_add_locations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='location',
        ),
    ]
