# Generated by Django 2.1.2 on 2019-08-14 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_scraper', '0029_remove_job_location'),
    ]

    operations = [migrations.RunSQL("""
            INSERT INTO 'Companies'('name', 'logo', 'logo100', 'description') VALUES ('Kamp Collection hotels', 'kamp_collection_hotels.png', 'kamp_collection_hotels_100.png', '<p>Kämp Collection Hotels (previously Kämp Group) is a Finnish hospitality group which consists of Finland’s most reputable hotels, restaurants and luxury spas.</p>');
            INSERT INTO 'Companies'('name', 'logo', 'logo100', 'description') VALUES ('Santapark', 'santapark.png', 'santapark_100.png', '<p>SantaPark Arctic World is a family-owned company.</p><p>Since 1997 we have provided lifetime experiences with uncompromising professionalism and attention to details. Located in Rovaniemi, the official hometown of Santa Claus, the values of Christmas are the core of the company vision.</p>');
            INSERT INTO 'Companies'('name', 'logo', 'logo100', 'description') VALUES ('Northern Lights Village', 'northern_lights_village.png', 'northern_lights_village_100.png', '<p>The Northern Lights Village provides a unique opportunity to experience the magnificence of the Northern Lights and the wild nature of Lapland at close range, without sacrificing comfort.</p>');
            INSERT INTO 'Companies'('name', 'logo', 'logo100', 'description') VALUES ('Kakslauttanen', 'kakslauttanen.png', 'kakslauttanen_100.png', '<p>Kakslauttanen is a family hotel in Finnish Lapland, 250 kilometres north of the Arctic Circle.</p><p>Although we are far from it all, our place is easy to reach. The nearest international airport is in Ivalo, just a 30-minute ride away.</p>');
            INSERT INTO 'Companies'('name', 'logo', 'logo100', 'description') VALUES ('Keysight Technologies', 'keysight_technologies.png', 'keysight_technologies_100.png', '<p>Keysight’s singular focus on measurement helps scientists, researchers and engineers address their toughest challenges with precision and confidence.</p><p>With the help of our products and services, they are better able to deliver the breakthroughs that make a measurable difference.</p>');
            INSERT INTO 'Companies'('name', 'logo', 'logo100', 'description') VALUES ('Nipromec Group', 'nipromec_group.png', 'nipromec_group_100.png', '<p>Nipromec Oy Ltd is a global consulting and engineering company operating in energy-, industry- and offshore fields.</p><p>By recognizing customer’s needs and working in close co-operation with the customer, Nipromec Group will provide the most suitable specialized consulting service to guarantee the best possible result all over the world.</p>');
            INSERT INTO 'Companies'('name', 'logo', 'logo100', 'description') VALUES ('Sellforte', 'sellforte.png', 'sellforte_100.png', '<p>Sellforte provides advanced analytics to optimize marketing, campaigns and promotions in retail.</p><p>We are a data science company, driven by curiosity to understand how things work, and we seek to turn our findings into automated services that lead to better and more fact-based decisions.</p>');
            INSERT INTO 'Companies'('name', 'logo', 'logo100', 'description') VALUES ('Dazzle Rocks', 'dazzle_rocks.png', 'dazzle_rocks_100.png', '<p>A social games studio in the center of Helsinki, Finland.</p><p>We love games and challeging ourselves to bring the most unique, massive, artistic ideas to reality. We are 100% focused on mobile games.</p>');
            INSERT INTO 'Companies'('name', 'logo', 'logo100', 'description') VALUES ('Codemate', 'codemate.png', 'codemate_100.png', '<p>Codemate is an international software development company from Finland that specializes in developing web systems and mobile applications as a service.</p>');
        """)]

