# Generated by Django 2.1.2 on 2019-08-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_scraper', '0032_auto_20190826_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='language',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
