# Generated by Django 2.1.2 on 2019-09-08 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_scraper', '0033_job_language'),
    ]

    operations = [migrations.RunSQL("""
            INSERT INTO "Companies"("name", "logo", "logo100", "description") VALUES ('Aito', 'aito.png', 'aito_100.png', '<p>Aito is a predictive database for developers who value quick time to market.</p><p>Aito replaces the current machine learning tools that have a steep learning curve and generate single-purpose models.</p>');
            INSERT INTO "Companies"("name", "logo", "logo100", "description") VALUES ('Collective Crunch', 'collective_crunch.png', 'collective_crunch_100.png', '<p>At CollectiveCrunch, we are all about harnessing the power of technology in the world of natural resources.</p><p>In both the forestry and energy industries, we are applying our unique AI solutions to make operations smoother, use resources more efficiently, and deliver insights more accurately.</p>');
            INSERT INTO "Companies"("name", "logo", "logo100", "description") VALUES ('Curious AI', 'curious_ai.png', 'curious_ai_100.png', '<p>Curious AI builds easy to use tools for intelligent automation. Our AI solutions offer immediate savings over existing IT systems and processes.</p><p>And the new intelligence unlocks completely new business opportunities for your organisation.</p>');
            INSERT INTO "Companies"("name", "logo", "logo100", "description") VALUES ('DAIN Studios', 'dain_studios.png', 'dain_studios_100.png', '<p>DAIN Studios is  a digital and analytics consultancy based in Helsinki,  Berlin and Munich.</p><p>We specialize in big data, analytics and AI, and have  a full portfolio of data and analytics offerings – from business strategy to data science and analytics implementation.</p>');
            INSERT INTO "Companies"("name", "logo", "logo100", "description") VALUES ('Fourkind', 'fourkind.png', 'fourkind_100.png', '<p>We amplify current businesses with emerging technology, such as advanced analytics, artificial intelligence and platform economy consulting.</p><p>We help decision-makers build organizations, products, services, processes and revenue around things we do best: data, machine learning, and new business concepts.</p>');
            INSERT INTO "Companies"("name", "logo", "logo100", "description") VALUES ('Inscripta', 'inscripta.png', 'inscripta_100.png', '<p>Inscripta Medical is a modern and cost-efficient solution designed for dictating, optimizing and storing patient notes onto a company''s health record system.</p>');
            INSERT INTO "Companies"("name", "logo", "logo100", "description") VALUES ('Speechgrinder', 'speechgrinder.png', 'speechgrinder_100.png', '<p>We create voice interfaces for professional tools and services using deep learning and natural language processing technologies.</p>');
            INSERT INTO "Companies"("name", "logo", "logo100", "description") VALUES ('Top Data Science', 'top_data_science.png', 'top_data_science_100.png', '<p>Top Data Science is a data science company focusing on AI powered Computer Vision, Machine Learning and Analytics technologies and development services for corporate customers and technology companies.</p>');
            INSERT INTO "Companies"("name", "logo", "logo100", "description") VALUES ('Utopia Analytics', 'utopia_analytics.png', 'utopia_analytics_100.png', '<p>We provide tools and services that enable our customers to analyse text content automatically.</p><p>With the help of text analytics, data mining and machine learning, our tools are automated, fully customizable and easy to implement – all powered by Utopia AI.</p>');
            INSERT INTO "Companies"("name", "logo", "logo100", "description") VALUES ('Valohai', 'valohai.png', 'valohai_100.png', '<p>Valohai is the only machine learning platform built for private installations with company''s intellectual property''s safety at the core.</p>');
        """)]
