# Generated by Django 2.2.6 on 2019-10-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_scraper', '0035_auto_20191009_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_url',
            field=models.URLField(max_length=1000),
        ),
    ]
