# Generated by Django 2.2.6 on 2019-11-21 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_scraper', '0036_auto_20191009_1901'),
    ]

    operations = [migrations.RunSQL("""
            INSERT INTO "Companies"("name", "logo", "logo100", "description") VALUES ('Amino', 'amino.png', 'amino_100.png', '<p>Amino is an innovative global provider of modern, scalable media and entertainment technology solutions. With our award-winning IP/cloud video solutions and deep deployment expertise, we are the partner operators trust to design and deliver modern TV experiences that gain them an advantage in meeting the demands of today''s connected consumer</p>');
        """)]